ArticleViewerWebApplication/Controllers/MyArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ArticleViewerWebApplication.Models;
using ArticleViewerWebApplication.Models.Entities;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace ArticleViewerWebApplication.Controllers
{
    [Authorize]
    public class MyArticlesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MyArticles
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var articles = db.articles.Where(a => a.userId.Equals(userId)).ToList();

            

            return View(articles);
        }

        // GET: MyArticles/Create
        public ActionResult Create()
        {
            ViewBag.numOfParagraphs = 3;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "articlePreview,title,body")] Article article, HttpPostedFileBase imageData, List<string> paragraphs)
        {
            if (ModelState.IsValid)
            {
                // Configure Article metadata
                article.userId = User.Identity.GetUserId();
                article.date = DateTime.Now;
                article.author = User.Identity.GetUserName();

                if (imageData != null)
                { 

                    byte[] imageByteArray = ConvertToByte(imageData);

                    article.image = 
                    new Image {
                        imageDate = DateTime.Now,
                        imageCaption = "Caption",
                        imageData = imageByteArray
                    };
                }

                ArticleContent ac = new ArticleContent
                {
                    paragraphs = paragraphs
                };

                article.articleContent = JsonConvert.SerializeObject(ac);

                db.articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfigureParagraphs(string page, int numOfParagraphs, int? articleId)
        {
            ViewBag.numOfParagraphs = numOfParagraphs;

            if (page != null && page.Equals("Edit"))
            {
                Article article = db.articles.Find(articleId);

                GetArticle(articleId);
                ViewBag.numOfParagraphs = numOfParagraphs;

                return View("Edit", article);
            }
            return View("Create");

        }

        // GET: MyArticles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Article article = GetArticle(id);

            return View(article);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "articleId,articlePreview,title")] Article article, List<string> paragraphs)
        {
            if (ModelState.IsValid)
            {
                ArticleContent ac = new ArticleContent
                {
                    paragraphs = paragraphs
                };

                Article foundArticle = db.articles.Find(article.articleId);

                foundArticle.title = article.title;
                foundArticle.articlePreview = article.articlePreview;
                foundArticle.articleContent = JsonConvert.SerializeObject(ac);



                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: MyArticles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: MyArticles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.articles.Find(id);
            db.articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public byte[] ConvertToByte(HttpPostedFileBase file)
        {
            byte[] imageByte = null;
            BinaryReader rdr = new BinaryReader(file.InputStream);
            imageByte = rdr.ReadBytes((int)file.ContentLength);
            return imageByte;
        }

        public Article GetArticle(int? id)
        {
            Article article = db.articles.Find(id);

            if (article.articleContent != null)
            {
                article.content = JsonConvert.DeserializeObject<ArticleContent>(article.articleContent);
                article.content.paragraphs.ForEach(p => p = "\t" + p);
                ViewBag.numOfParagraphs = article.content.paragraphs.Count;
            }
            return article;
        }


    }
}

ArticleViewerWebApplication/Views/MyArticles/Create.cshtml
@model ArticleViewerWebApplication.Models.Article

@{
    ViewBag.Title = "Create";
}
<div class="w3-card w3-white" style="margin: 25px;">
    <div style="padding: 25px;">
        <h2 class="articleTitle">Create an Article</h2>

        @using (Html.BeginForm("ConfigureParagraphs", "MyArticles", FormMethod.Post))
        {
            @Html.AntiForgeryToken();

            <label>Number of paragraphs: </label>
            <input type="number" name="numOfParagraphs" value='@ViewBag.numOfParagraphs' min="1" max="25" />
            <input type="submit" class="w3-button w3-border" value="Change" />
        }

        @{
            int numberOfParagraphs;
            if (ViewBag.numOfParagraphs != null)
            {
                numberOfParagraphs = ViewBag.numOfParagraphs;
            }
            else
            {
                numberOfParagraphs = 3;
            }
        }


        @using (Html.BeginForm("Create", "MyArticles", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="control-label col-md-2">
                        <label>Title Your Article: </label>
                    </div>
                    <div class="col-md-10">
                        <input name="title" required />
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2">
                        <label>Preview for Home Page:</label>
                    </div>
                    <div class="col-md-10">
                        <textarea name="articlePreview" type="text" style="min-width: 25%; max-width: 100%; width: 100%; height: 100px; min-height: 50px; max-height: 500px;" required></textarea>
                    </div>
                </div>

                <hr />

                @for (int i = 0; i < numberOfParagraphs; i++)
                {
                    <div class="form-group">
                        <div class="control-label col-md-2">
                            <label>Paragraph #@(i+1):</label>
                        </div>
                        <div class="col-md-10">
                            <textarea name="[@i]" type="text" style="min-width: 25%; max-width: 100%; width: 100%; height: 100px; min-height: 50px; max-height: 500px;" required></textarea>
                        </div>
                    </div>
                }

                <hr />

                <div class="form-group">
                    <div class="control-label col-md-2">
                        <label>Upload An Image:</label>
                    </div>
                    <div class="col-md-10">
                        <input type="file" name="imageData" />
                    </div>
                </div>

                <hr />

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArticleViewerWebApplication/Views/MyArticles/Delete.cshtml
@model ArticleViewerWebApplication.Models.Article

@{
    ViewBag.Title = "Delete";
}
<div class="w3-container w3-white" style="margin: 25px;">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Article</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.userId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.userId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.author)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.author)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.title)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

ArticleViewerWebApplication/Views/MyArticles/Edit.cshtml
@model ArticleViewerWebApplication.Models.Article

@{
    ViewBag.Title = "Edit";
}
<div class="w3-card w3-white" style="margin: 25px;">
    <div style="padding:25px;">
        <h2 class="articleTitle">Edit Article</h2>

        @using (Html.BeginForm("ConfigureParagraphs", "MyArticles", FormMethod.Post))
        {
            @Html.AntiForgeryToken();

            <label>Number of paragraphs: </label>
            <input name="Page" value="Edit" hidden />
            <input name="articleId" value='@Model.articleId' hidden/>
            <input type="number" name="numOfParagraphs" value='@ViewBag.numOfParagraphs' min="1" max="25" />
            <input type="submit" class="w3-button w3-border" value="Change" />
        }

        @{
            int numberOfParagraphs;
            if (ViewBag.numOfParagraphs != null)
            {
                numberOfParagraphs = ViewBag.numOfParagraphs;
            }
            else
            {
                numberOfParagraphs = 3;
            }
        }


        @using (Html.BeginForm("Edit", "MyArticles", FormMethod.Post))
        {
            @Html.AntiForgeryToken();

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <input name="articleId" value='@Model.articleId' hidden />

                <div class="form-group">
                    <div class="control-label col-md-2">
                        <label>Title Your Article: </label>
                    </div>
                    <div class="col-md-10">
                        <input name="title" value="@Model.title" required />
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label col-md-2">
                        <label>Preview for Home Page:</label>
                    </div>
                    <div class="col-md-10">
                        <textarea name="articlePreview" type="text" style="min-width: 25%; max-width: 100%; width: 100%; height: 100px; min-height: 50px; max-height: 500px;" required>@Model.articlePreview</textarea>
                    </div>
                </div>

                <hr />


                @for (int i = 0; i < numberOfParagraphs; i++)
                {
                    <div class="form-group">
                        <div class="control-label col-md-2">
                            <label>Paragraph #@(i+1):</label>
                        </div>
                        <div class="col-md-10">
                            <textarea name="[@i]" type="text" style="min-width: 25%; max-width: 100%; width: 100%; height: 100px; min-height: 50px; max-height: 500px;" required>
                                @if (i < Model.content.paragraphs.Count && Model.content.paragraphs.ElementAt(i) != null)
                                {
                                    @Model.content.paragraphs.ElementAt(i)
                                }
                            </textarea>
                        </div>
                    </div>
                }

                <hr />

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save Changes" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArticleViewerWebApplication/Views/MyArticles/Index.cshtml
@model IEnumerable<ArticleViewerWebApplication.Models.Article>

@{
    ViewBag.Title = "Index";
}
<div class="w3-card w3-white" style="margin: 25px;">
    <div style="padding: 25px">
        <h2 class="articleTitle">My Articles</h2>

        <table class="table">
            <tr>
                <th>
                    <label>Title</label>
                </th>
                <th>
                    <label>Date</label>
                </th>
                <th>
                    <label>Preview</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.articlePreview)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.articleId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.articleId })
                    </td>
                </tr>
            }

        </table>

        <hr />

        <button class="w3-button w3-border padBig" onclick="location.href = '@Url.Action("Create", "MyArticles")'; return false;">Create A New Article >></button>
    </div>
</div>